### PR TITLE
Introduce objects and integrate with signals

### PR DESCRIPTION
**Pull request by jakobkaths**
Hi all, this is a quite large change now, I hope it's not too much over the top. It also does introduce actually quite a change on how to introduce signals compared to the previous way proposed by @ishaan95 . I find it more convenient like this, but I'm open for discussion. Maybe it helps the motivation to review this change (at least it helped mine to make it) if you look at the attached screenshot, which is the result of our auto-generated visualization of the highway example.
DYNA4_Screenshot_HighwayExample

### CODE REVIEW

**Comment by mander76** [comment]
Hi @jakobkaths, I think this looks good, and nice to get the repeated feature into it directly!

I only have some small comments:

1. I think it would be nice to divide the examples, one for the highway generation, and one focused on the object (maybe have a simpler road?). So that both simple examples as well as more complex examples are provided.
2. please add test for the repeated feature aswell.
3. A more generic design thing, for the generators: Is it possible to create a separate generator for the objects, instead of having it as true/false? Maybe a list of objects (similarly to the geometries), and the default is guardrails and poles?

@ishaan95 What do you think about the changes made for your applications?

**Comment by jakobkaths** [comment]
Hi @mander76 , thanks for checking the changes and your suggestions. Regarding your comments:
1. I reset the highway example and created a derivative of multiple_geometries_one_road.py
2. id should not be mandatory anymore, see also 4.
3. ok
4. I thought about this and found a different way to address this and to add (in my opinion) a lot more convenience and generic applicability. I introduced a function that can add repeated objects along an entire road on either left, right or both sides based on some Object instance. It takes away the tedious part of figuring out the total width, the road length, etc. Unfortunately, it can only be executed after adjusting the roads, that's the only drawback in my opinion.

Hope you like the changes.

**Comment by ishaan95** [comment]
The changes look good. Having common base class for signals and objects makes sense.

**Comment by jakobkaths** [comment]
I just realized that my introduced deepcopy causes problems with the uniqueness of the IDs, I'll try to provide a fix for that.

**Comment by jakobkaths** [comment]
Should be fixed with the latest commit now.

**Comment by mander76** [comment]
I haven't had time to look at the new stuff yet, have alot at work right now. :( will check it out as soon as I get some time over!

**Comment by mander76** [comment]
Nice addtion with the add_object_roadside ! that will be very useful.

only two small comments left before I merge it.

1. Road.add_object is missing the Parameter description
2. in add_object_roadside() is it enough with a warning and return? or should an error be raised? either way, could be added to the help that adjust_roads_and_lanes has to be used prior to this.

**Comment by jakobkaths** [comment]
Great that you like it. Thanks for looking into it. I tried addressing your comments, not so sure about the exception, but I introduced one, you could take that or revert those lines if you want to go back to the simple print.

**Pull request merged**
