### PR TITLE
Create child elements type and line of roadmark only when necessary

### PR DESCRIPTION
**Pull request by jakobkaths**
* provide default values
* include logic to decide whether or not to create child element
* fixed some small typos

### CODE REVIEW

**Comment by jakobkaths** [comment]
Hi, I very much like what you did here, thanks for this work! We have experimented a little in creating some OpenDRIVE files and were quite happy with it. However, some roadmarks issues causedinaccurate visualization on our side. I tried to make optional things actually optional and ensured that the subelements type / line are only generated when necessary. I tried to touch your interface as little as possible, so your examples and tests still work (with almost same results). I'm happy to discuss further (e.g. adapt examples to actually use simplified roadmark records), but I thought it would be a good idea to discuss based on this PullRequest.

**Comment by mander76** [comment]
Hi

Thanks for the pull-request! It's very much appreciated since we don't have alot of time to implement new things into the package (and to be fair, opendrive is huge)

Default values for these things are always a little tricky, (first version had no default values basically). But gradually more can be added to make use of the framework more usable. And think this is a nice addition! Only comment I have directly is that length doesn't really make any sence? or does it have an impact in your usecase? what tool are you using for visualizaton?

We will try it out in esmini and see if it has any impacts anything.

**Comment by jakobkaths** [comment]
Hi,

sorry, I forgot to mention, I work for Vector in Germany and our vehicle and environment simulator DYNA4 uses OpenDRIVE without conversion as a road description for the models (e.g. tire contact queries, etc.), but also for generating a visualization. The length / space attributes are placed in the optional child argument. For us it's enough without that child, to draw a default roadmark. For example, if we know it's of type "broken", we choose a realistic length and space for the visualization of that line. If the optional arguments length and space are provided, we render a broken line with exactly those specifications. My intention was to still allow for this (so length should still be functional), but don't require it anymore and also allow for the simplified definition. I hope it will still work like that with esmini.

Best regards

Jakob

**Comment by mander76** [comment]
There was one of the example roads that had some issue in esmini, we will try to check it out today and see what the differences are.

**Comment by inatale93** [comment]
Hello, 

false alarm, everything works fine on our side, I will merge the request! thank you a lot for your contribution to the project :) 

/Irene

**Pull request merged**
